package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

type FileUpload struct {
	Id            string    `json:"id"`
	FileName      string    `json:"fileName"`
	FileExtension string    `json:"fileExtension"`
	OwnerID	   	  string    `json:"ownerId"`
	FolderID	  string    `json:"folderId"`
	UploadUuid    string    `json:"uploadUuid"`
	UploadedAt    time.Time `json:"uploadedAt"`
}

func NewFileUpload(fileName, fileExtension string) (*FileUpload, error) {
	if fileName == "" {
		return nil, errors.New("file name cannot be empty")
	}
	if fileExtension == "" {
		return nil, errors.New("file extension cannot be empty")
	}

	return &FileUpload{
		Id:            "", // ID will be generated by the database when the file upload record is saved
		FileName:      fileName,
		FileExtension: fileExtension,
		OwnerID:       ownerId, // This should be set to the ID of the user who is uploading the file
		FolderID:      folderId, // This should be set to the ID of the folder where the file is being uploaded
		UploadUuid:    uuid.NewString(),
		UploadedAt:    time.Now(),
	}, nil
}
