package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

type Folder struct {
	Id            string    `json:"id"`
	FolderName    string    `json:"fileName"`
	OwnerID	   	  string    `json:"ownerId"`
	FolderID	  string    `json:"folderId"`
	UploadedAt    time.Time `json:"createdAt"`
}

func NewFolder(folderName, ownerId, folderID string) (*Folder, error) {
	if folderName == "" {
		return nil, errors.New("folder name cannot be empty")
	}
	if ownerId == "" {
		return nil, errors.New("owner ID cannot be empty")
	}
	if folderID == "" {
		return nil, errors.New("folder ID cannot be empty")
	}

	return &Folder{
		Id:          	"", // ID will be generated by the database when the folder create record is saved
		FolderName:  	folderName,
		OwnerID:	 	ownerId,
		FolderID:	 	folderID,
		UploadedAt:  	time.Now(),
	}, nil
}
