package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	Id            string    `json:"id"`
	OwnerID      string    `json:"userId"`
	UserID       string    `json:"userId"`
	AccessLevel   string    `json:"accessLevel"` // e.g., "read", "write", "admin"
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

func NewPermission(ownerID, userID, accessLevel string) (*Permission, error) {
	if ownerID == "" {
		return nil, errors.New("owner ID cannot be empty")
	}
	if userID == "" {
		return nil, errors.New("user ID cannot be empty")
	}
	if accessLevel == "" {
		return nil, errors.New("access level cannot be empty")
	}

	return &Permission{
		Id:          "", // ID will be generated by the database when the permission record is saved
		OwnerID:     ownerID,
		UserID:      userID,
		AccessLevel: accessLevel,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}, nil
}
\\